[package]
name = "rust_playground"
version = "0.1.0"
authors = ["Arvonit <me@arvind.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
